### ISSUE TITLE
ISSUE config

### ISSUE THREAD

**Issue by Sothopery** [Leva25se/FogLock#3]
![image](https://github.com/Leva25se/FogLock/assets/36519325/1c372b9e-f9da-4327-9d4a-7bca0613d634)
Alpha misspelled in the auto-generated config

Also I'm not sure how to add new things to it <: O

**Comment by Sothopery** [comment]
I think i get how to do the config. it's just a little complicated to find out hehe

**Comment by Sothopery** [comment]
actually i dont. how do you add the nether to this config? (•_•)

**Comment by Leva25se** [comment]
> actually i dont. how do you add the nether to this config? (•_•)

There are two ways to do it:
1) you can use the biome tag in the configuration (biomeTagsEnable true).  For example: 
```
    {
      "path": "is_nether",
      "namespace": "minecraft",
      "priority": 1,
     }
```
Example for using fabric biome tag:
```
    {
      "path": "in_nether",
      "namespace": "c",
      "priority": 1,
     }
```
2) you can use a world or biome identifier (worldAndBiomeEnable true). For example: 
```
    {
      { "path": "the_nether",
      "namespace": "minecraft",
      "priority": 1,
     }
```
