### ISSUE TITLE
ISSUE crash if no state is set

### ISSUE THREAD

**Issue by Sothopery** [Leva25se/FogLock#4]
Game crashes when on a chunk border while underwater

Crash Log: [](https://crashy.net/2649802c-99b2-4b5b-9ad8-f255da49ae33)

JSON FILE:
{
  "calculation": "none",
  "worldAndBiomeEnable": true,
  "identifiers": [
    {
      "path": "is_end",
      "namespace": "minecraft",
      "priority": 1,
      "NONE": {
        "start": 1,
        "end": 128
      }
    }
  ],
  "biomeTagsEnable": true,
  "NONE": {
    "start": "1",
    "end": 80
  },
  "version": "1.5",
  "AutoAddNewFeaturesToConfiguration": true
}

**Comment by Sothopery** [comment]
https://crashy.net/2649802c-99b2-4b5b-9ad8-f255da49ae33

**Comment by Leva25se** [comment]
Now it should work even if not all states are set.
